# Generated by Django 4.1.2 on 2024-03-24 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("phone", models.CharField(blank=True, max_length=11)),
                ("msg", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("gender", models.CharField(max_length=20)),
                ("mobile", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "usern",
                    models.OneToOneField(
                        blank=True,
                        max_length=80,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=200)),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_ride.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mycar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_num", models.CharField(max_length=10, unique=True)),
                ("company", models.CharField(max_length=30)),
                ("car_name", models.CharField(max_length=30)),
                ("car_type", models.CharField(max_length=30)),
                ("from_place", models.CharField(max_length=30)),
                ("to_place", models.CharField(max_length=30)),
                ("from_date", models.DateField(null=True)),
                ("to_date", models.DateField(null=True)),
                ("price", models.FloatField()),
                (
                    "car_img",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="cars"
                    ),
                ),
                ("total_seats", models.IntegerField()),
                ("seats_booked", models.IntegerField(default=0)),
                ("departure_time", models.TimeField(default=django.utils.timezone.now)),
                ("arrival_time", models.TimeField(default=django.utils.timezone.now)),
                ("is_parcel", models.BooleanField(default=False)),
                ("kilograms", models.FloatField(blank=True, default=0)),
                ("luggage_details", models.CharField(max_length=30)),
                (
                    "cust",
                    models.ForeignKey(
                        blank=True,
                        max_length=100,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="car_ride.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=80)),
                ("pick_add", models.CharField(max_length=100)),
                ("drop_add", models.CharField(max_length=100)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("num_seats_booked", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "car",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="car_ride.mycar",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="car_ride.customer",
                    ),
                ),
            ],
        ),
    ]
