# Generated by Django 5.0.1 on 2024-03-11 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_ride', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='bookedride',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='bookedride',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='from_location',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('usern', models.OneToOneField(blank=True, max_length=80, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterDriver',
        ),
        migrations.DeleteModel(
            name='BookedRide',
        ),
        migrations.DeleteModel(
            name='CarType',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
