# Generated by Django 5.0.3 on 2024-03-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalreservation",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("sedan", "Sedan"),
                    ("suv", "SUV"),
                    ("truck", "Truck"),
                    ("van", "Van"),
                    ("sports", "Sports"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
