# Generated by Django 5.0.3 on 2024-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0002_insurancepolicy_location_photo_customerreview_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.AddField(
            model_name="car",
            name="color",
            field=models.CharField(default="unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="car_photos/"),
        ),
    ]
