# Generated by Django 5.0.3 on 2024-03-14 20:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0003_delete_photo_car_color_car_photo"),
        ("car_ride", "0003_contactus_mycar_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalreservation",
            name="status",
        ),
        migrations.AddField(
            model_name="rentalreservation",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("sedan", "Sedan"),
                    ("suv", "SUV"),
                    ("truck", "Truck"),
                    ("van", "Van"),
                ],
                default="sedan",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rentalreservation",
            name="dropoff_location",
            field=models.CharField(
                choices=[
                    ("London", "London"),
                    ("Windsor", "Windsor"),
                    ("Toronto", "Toronto"),
                    ("Hamilton", "Hamilton"),
                ],
                default="Windsor",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="rentalreservation",
            name="pickup_location",
            field=models.CharField(
                choices=[
                    ("London", "London"),
                    ("Windsor", "Windsor"),
                    ("Toronto", "Toronto"),
                    ("Hamilton", "Hamilton"),
                ],
                default="Windsor",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="rentalreservation",
            name="pickup_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="rentalreservation",
            name="return_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="rentalreservation",
            name="customer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="car_ride.customer",
            ),
        ),
        migrations.AlterField(
            model_name="rentalreservation",
            name="rental_end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="rentalreservation",
            name="rental_start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
