# Generated by Django 5.0.3 on 2024-03-16 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0005_remove_rentalreservation_car_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="fname",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customuser",
            name="mobile",
            field=models.CharField(default="", max_length=11),
        ),
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="usern",
            field=models.OneToOneField(
                blank=True,
                default="",
                max_length=80,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(default="", max_length=80, unique=True),
        ),
    ]
