# Generated by Django 5.0.3 on 2024-03-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0008_remove_customuser_fname_remove_customuser_lname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="dl_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="issueing_country",
            field=models.CharField(
                blank=True,
                choices=[("Canada", "Canada"), ("USA", "USA")],
                default="Windsor",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mobile",
            field=models.CharField(blank=True, default="", max_length=11),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
