# Generated by Django 5.0.3 on 2024-03-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0009_alter_customuser_address_alter_customuser_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
    ]
