# Generated by Django 5.0.3 on 2024-03-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0010_customuser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
