# Generated by Django 5.0.3 on 2024-03-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0011_alter_customuser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("sedan", "Sedan"),
                    ("suv", "SUV"),
                    ("truck", "Truck"),
                    ("van", "Van"),
                    ("sports", "Sports"),
                ],
                default="sedan",
                max_length=20,
            ),
        ),
    ]
