# Generated by Django 4.1.2 on 2024-03-22 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("car_ride", "0004_notification"),
        ("car_rental", "0013_alter_rentalreservation_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalreservation",
            name="customer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="car_ride.customer",
            ),
        ),
    ]
