# Generated by Django 5.0.3 on 2024-03-22 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PATH", "0006_rename_customeruser_customuser"),
        ("car_rental", "0014_alter_rentalreservation_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalreservation",
            name="customer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="PATH.customuser",
            ),
        ),
    ]
