# Generated by Django 5.0.2 on 2024-03-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PATH", "0002_remove_customuser_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
    ]
