# Generated by Django 5.0.3 on 2024-03-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PATH", "0003_customuser_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
            ],
        ),
    ]
