# Generated by Django 4.1.2 on 2024-03-21 07:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("PATH", "0005_customeruser_notification_delete_customuser_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Customeruser", new_name="Customuser",),
    ]
