# Generated by Django 5.0.3 on 2024-03-25 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='destination',
            new_name='destination_city',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='source',
            new_name='source_city',
        ),
        migrations.AddField(
            model_name='parcel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='parcel_service'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='is_accepted',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Requested', max_length=50),
        ),
        migrations.AddField(
            model_name='parcel',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='ride_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
